/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gens_window (void);
GtkWidget* create_about (void);
GtkWidget* create_game_genie (void);
GtkWidget* create_color_adjust (void);
GtkWidget* create_general_option (void);
GtkWidget* create_controllers_settings (void);
GtkWidget* create_directories_configuration (void);
GtkWidget* create_bios_files (void);
GtkWidget* create_msgbox (void);
GtkWidget* create_opengl_resolution_custom (void);
GtkWidget* create_sdl_test (void);
GtkWidget* create_cdrom_window (void);